### ISSUE TITLE
mint-dev-tools uninstallable in rebecca

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-dev-tools#1]
When i try to install mint-dev-tools on Rebecca I get following error message

The following packages have unmet dependencies:
 mint-dev-tools : Depends: sublime-text but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by clefebvre** [comment]
You're missing the extra repository for rebecca then: http://extra.linuxmint.com/pool/main/s/sublime-text/sublime-text_3083_amd64.deb
