### ISSUE TITLE
mint-build: install test of generate package not do full testing and probably not working correctly in some cases

### ISSUE THREAD

**Issue by Fantu** [linuxmint/mint-dev-tools#14]
After trying to improve circleci jobs configuration I saw on log of "strange" failed build:
...
   #######################################################################
   ### Installing
   #######################################################################
...

this seems from mint-build use:
sudo apt install --yes --allow-downgrades ../*.deb || sudo dpkg -i ../*.deb
I suppose replace with piuparts of .changes (of files generate by dpkg-buildpackage) will do complete and correct generated packages install/remove/purge testing

I don't know if possible change mint-build in a PR here and do a fast test of that change fast using circleci

**Comment by clefebvre** [comment]
Closing because it's really old.
