### ISSUE TITLE
mint-dev-tools missing python-polib dependency

### ISSUE THREAD

**Issue by mahfiaz** [linuxmint/mint-dev-tools#18]
mint-dev-tools package depends on `python3-polib` package but should depend on `python-polib`.
The only file which imports `polib` is `mint-check-translations` which still uses python2 and fails with the following error if `python-polib` is not installed:

```
Traceback (most recent call last):
  File "/usr/bin/mint-check-translations", line 4, in <module>
    import polib
ImportError: No module named polib

```

**Comment by kolayne** [comment]
I can't reproduce this with mint-dev-tools 1.2.5. Is it fixed?

**Comment by clefebvre** [comment]
it was ported to python3.
